# NBA Player Aliases for Hate Detection
# Optimized: shortest unique fragments + non-overlapping nicknames only

version: "1.2"
season: "2024-25"

# Aliases requiring word boundary matching (\b) to avoid false positives
short_aliases:
  # Two-letter
  - ad
  - ai
  - bi
  - cp
  - dg
  - ja
  - jp
  - jt
  - kd
  - og
  - pb
  - pg
  - zo
  - zu
  - tt
  # Three-letter
  - ant
  - alp
  - abe
  - bam
  - ben
  - jjj
  - mpj
  - naz
  - rui
  - sga
  # Short words/names
  - amen
  - book
  - bron
  - dame
  - dort
  - fox
  - kat
  - the greek
  - russ
  # Common words (need boundaries)
  - curry
  - smart
  - green
  - brown
  - hart
  # Common names (need boundaries)
  - davis
  - george
  - paul
  - mitchell
  - edwards
  - murray
  - gordon
  - turner
  - holiday
  - leonard
  - jordan

players:
  # Alphabetical by last name

  Bam Adebayo:
    - adebayo
    - bam

  Giannis Antetokounmpo:
    - giannis
    - greek freak
    - alphabet
    - the greek
    - antetokounmpo

  OG Anunoby:
    - anunoby
    - og

  Deandre Ayton:
    - deandre ayton
    - ayton

  Marvin Bagley III:
    - bagley

  Lonzo Ball:
    - lonzo
    - zo
    # Negative
    - lavar's son

  LaMelo Ball:
    - lamelo
    # Negative

  Paolo Banchero:
    - banchero
    - paolo
    - pb

  Desmond Bane:
    - bane
    - desmond

  Harrison Barnes:
    - harrison barnes

  Scottie Barnes:
    - barnes
    - scottie

  Bradley Beal:
    - bradley beal
    - beal

  Patrick Beverley:
    - beverley
    - pat bev
    - patbev

  Devin Booker:
    - booker
    - dbook
    - book
    # Negative
    - empty stats
    - bubble boy

  Mikal Bridges:
    - mikal bridges
    - mikal
    - the warden

  Dillon Brooks:
    - dillon brooks
    - dillon

  Jaylen Brown:
    - jaylen brown
    - jaylen
    # Negative
    - robin to tatum

  Jalen Brunson:
    - brunson

  Jimmy Butler:
    - jimmy butler
    - butler
    - jimmy buckets
    - jimmy g
    - himmy
    # Negative
    - toxic jimmy
    - jimmy diva

  Clint Capela:
    - capela

  Alex Caruso:
    - caruso
    - the accountant
    - bald mamba
    - carushow

  Mike Conley:
    - mike conley
    - conley
    - bite bite

  Stephen Curry:
    - steph
    - steph curry
    - curry
    - wardell
    - chef curry
    - skyfucker
    - baby faced assassin
    # Negative
    - stephew
    - gravity merchant

  Cade Cunningham:
    - cunningham
    - cade
    - motorcade

  Anthony Davis:
    - ad
    - davis
    - the brow
    - unibrow
    # Negative
    - adisney
    - street clothes
    - day to davis
    - day-to-davis

  DeMar DeRozan:
    - derozan
    - demar
    - debo
    - compton's finest

  Donte DiVincenzo:
    - donte divincenzo
    - divincenzo
    - donte

  Luka Doncic:
    - luka
    - doncic
    - the don
    - wonderboy
    # Negative
    - fat luka
    - chubby luka
    - whiny luka

  Lu Dort:
    - lu dort
    - dort
    - luguentz

  Kevin Durant:
    - kd
    - durant
    - durantula
    - slim reaper
    - easy money sniper
    # Negative
    - cupcake
    - snake

  Zach Edey:
    - zach edey
    - edey

  Anthony Edwards:
    - ant
    - edwards
    - antman
    - ant edwards
    - ant-man
    - a1 from day 1

  Joel Embiid:
    - embiid
    - joel
    - the process
    - jojo
    - troel
    # Negative
    - jobiid
    - emflop
    - the processor

  De'Aaron Fox:
    - de'aaron
    - fox
    - swipa

  Evan Fournier:
    - fournier

  Darius Garland:
    - garland
    - dg

  Paul George:
    - pg
    - paul george
    - george
    - pg13
    # Negative
    - playoff p
    - pandemic p
    - wayoff p
    - pushoff p

  Josh Giddey:
    - josh giddey
    - giddey
    - slob wizard
    - himothee chalamet

  Shai Gilgeous-Alexander:
    - sga
    - shai
    - gilgeous-alexander

  Rudy Gobert:
    - gobert
    - rudy
    - stifle tower
    - gobzilla
    - rudymentary

  Aaron Gordon:
    - aaron gordon
    - gordon

  Jalen Green:
    - jalen green

  Draymond Green:
    - draymond
    - dray
    - bdd
    - day day
    # Negative
    - donkey
    - nut puncher
    - triple single

  Rui Hachimura:
    - rui hachimura
    - rui
    - hachimura

  Tyrese Haliburton:
    - haliburton
    - hali
    - haliban
    - halipotter

  James Harden:
    - harden
    - the beard
    # Negative
    - james floppen
    - james soften
    - literally hitler

  Tobias Harris:
    - tobias harris
    - tobias

  Josh Hart:
    - hart

  Scoot Henderson:
    - scoot henderson
    - scoot

  Tyler Herro:
    - herro
    - boy wonder

  Buddy Hield:
    - buddy hield
    - hield
    - buddy love
    - buddy buckets

  Chet Holmgren:
    - chet
    - holmgren
    - abe
    - abraham
    - lincoln

  Jrue Holiday:
    - jrue
    - holiday

  Al Horford:
    - al horford
    - horford

  Brandon Ingram:
    - ingram
    - bi
    - slim reefer
    - sleepy b

  Kyrie Irving:
    - kyrie
    - irving
    - kai
    - uncle drew
    - world b flat
    # Negative
    - flat earther
    - mr sage
    - third eye
    - antisemite

  Jaren Jackson Jr:
    - jaren jackson
    - jjj
    - triple j

  Bronny James:
    - bronny james
    - bronny
    - lenepo

  LeBron James:
    - lebron
    - bron
    - lbj
    - the king
    - chosen one
    # Negative (le- prefix variants don't contain "lebron")
    - lemickey
    - lebrick
    - lechoke
    - leflop
    - lefraud
    - lequit
    - lestatpad
    - lecoast
    - legm
    - lediva
    - letravel
    - leturnover
    - legoat
    - washed king
    - king james

  Nikola Jokic:
    - jokic
    - joker
    - chokic
    - big honey
    - sombor shuffle

  Tre Jones:
    - tre jones

  Jonathan Kuminga:
    - kuminga
    - jonathan kuminga
    - kum bucket

  Caris LeVert:
    - levert
    - caris

  Kawhi Leonard:
    - kawhi
    - leonard
    - the klaw
    - board man
    - fun guy

  Damian Lillard:
    - lillard
    - dame
    - dame time
    - dame dolla
    - logo lillard

  Zach LaVine:
    - lavine
    - zach

  Kevon Looney:
    - looney
    - loon

  Brook Lopez:
    - brook lopez
    - lopez
    - splash mountain

  Lauri Markkanen:
    - lauri markkanen
    - markkanen
    - lauri

  Tyrese Maxey:
    - maxey

  De'Anthony Melton:
    - melton

  Khris Middleton:
    - middleton
    - khris
    - khash money

  Donovan Mitchell:
    - donovan mitchell
    - mitchell
    - spida

  Evan Mobley:
    - evan mobley
    - mobley

  Ja Morant:
    - morant
    - ja
    - temetrius
    # Negative
    - glock morant
    - ja moron
    - moron-t

  Keegan Murray:
    - keegan murray
    - keegan

  Dejounte Murray:
    - dejounte

  Jamal Murray:
    - jamal murray
    - jamal
    - blue arrow
    - maple curry

  Chris Paul:
    - cp3
    - cp
    - chris paul
    - point god
    # Negative
    - dirty cp3
    - cone paul
    - cooked cp3

  Jordan Poole:
    - poole
    - jp
    - poole party

  Michael Porter Jr:
    - michael porter
    - mpj
    - porter jr
    - never swing the rock

  Kristaps Porzingis:
    - porzingis
    - kristaps
    - kp
    - tingus pingus

  Bobby Portis:
    - portis
    - crazy eyes

  Julius Randle:
    - randle
    - julius
    - beyblade

  Austin Reaves:
    - reaves
    - ar15
    - hillbilly kobe

  Naz Reid:
    - naz reid
    - naz

  Mitchell Robinson:
    - mitchell robinson
    - mitch rob

  D'Angelo Russell:
    - dlo
    - d'angelo
    - ice in my veins
    # Negative
    - snitch russell

  Domantas Sabonis:
    - sabonis
    - domas

  Alperen Sengun:
    - sengun
    - alperen
    - alperen şengün
    - alp

  Pascal Siakam:
    - siakam
    - pascal
    - spicy p
    - spinakam

  Ben Simmons:
    - simmons
    - ben
    - fresh prince
    # Negative
    - socialite

  Marcus Smart:
    - marcus smart
    - marcus dumb

  Jalen Smith:
    - jalen smith
    - stix

  Jayson Tatum:
    - tatum
    - jt
    - jayson

  Amen Thompson:
    - amen thompson
    - amen

  Ausar Thompson:
    - ausar thompson
    - ausar

  Klay Thompson:
    - klay
    - splash brother
    - game 6 klay
    - china klay
    # Negative
    - boat klay

  Karl-Anthony Towns:
    - towns
    - kat
    - karl-anthony

  Myles Turner:
    - turner
    - myles

  Fred VanVleet:
    - vanvleet
    - fvv
    - steady freddy

  Franz Wagner:
    - franz wagner
    - franz

  Nikola Vucevic:
    - vucevic
    - vooch

  Victor Wembanyama:
    - wembanyama
    - victor
    - wemby
    - the alien
    - the frenchise

  Russell Westbrook:
    - westbrook
    - russ
    - brodie
    # Negative
    - westbrick
    - worstbrook
    - westbroke
    - no bbiq

  Derrick White:
    - derrick white

  Aaron Wiggins:
    - aaron wiggins

  Andrew Wiggins:
    - wiggins
    - wiggs
    # Negative
    - maple jordan

  Jalen Williams:
    - jalen williams
    - j-dub

  Zion Williamson:
    - zion
    - williamson
    - zanos
    - air gumbo
    # Negative
    - big chungas

  Trae Young:
    - trae
    - ice trae
    # Negative
    - bald spot
    - hair plugs

  Ivica Zubac:
    - zubac
    - zu
