# NBA Player Aliases for Hate Detection
# Optimized: shortest unique fragments + non-overlapping nicknames only

version: "1.1"
season: "2024-25"

# Aliases requiring word boundary matching (\b) to avoid false positives
short_aliases:
  # Two-letter
  - ad
  - ai
  - bi
  - cp
  - dg
  - ja
  - jp
  - kd
  - og
  - pg
  # Short words/names
  - ant
  - bam
  - book
  - dame
  - fox
  - kat
  - sga
  - zo
  - zu
  - tt
  - the greek
  # Common words (need boundaries)
  - curry
  - smart
  - green
  - brown
  - wall
  - hart
  # Common names (need boundaries)
  - davis
  - james
  - george
  - paul
  - mitchell
  - edwards
  - murray
  - gordon
  - turner
  - holiday
  - howard
  - leonard
  - jordan
  - rose

players:
  # Alphabetical by last name

  Bam Adebayo:
    - adebayo
    - bam

  Giannis Antetokounmpo:
    - giannis
    - greek freak
    - alphabet
    - the greek
    # Negative (no giannis substring)
    - freethrow merchant

  Carmelo Anthony:
    - melo
    - me7o

  OG Anunoby:
    - anunoby
    - og

  Marvin Bagley III:
    - bagley

  Lonzo Ball:
    - lonzo
    - zo
    # Negative
    - lavar's son

  LaMelo Ball:
    - lamelo
    # Negative

  Paolo Banchero:
    - banchero
    - paolo
    - pb

  Desmond Bane:
    - bane

  Scottie Barnes:
    - barnes
    - scottie

  Patrick Beverley:
    - beverley
    - pat bev
    - patbev

  Devin Booker:
    - booker
    - dbook
    - book
    # Negative
    - empty stats
    - bubble boy

  Mikal Bridges:
    - mikal bridges
    - mikal
    - the warden

  Dillon Brooks:
    - dillon brooks
    - dillon

  Jaylen Brown:
    - jaylen brown
    - jaylen
    - jb
    # Negative
    - robin to tatum

  Jalen Brunson:
    - brunson
    - jb

  Jimmy Butler:
    - jimmy butler
    - butler
    - jimmy buckets
    - buckets
    - himmy
    # Negative
    - toxic jimmy
    - jimmy diva

  Clint Capela:
    - capela

  Alex Caruso:
    - caruso
    - the accountant
    - bald mamba
    - carushow

  Stephen Curry:
    - steph
    - curry
    - wardell
    - chef curry
    - skyfucker
    # Negative
    - stephew
    - gravity merchant

  Cade Cunningham:
    - cunningham
    - cade

  Anthony Davis:
    - ad
    - davis
    - the brow
    - unibrow
    # Negative
    - adisney
    - street clothes
    - day to davis
    - day-to-davis
    - bubble champion

  DeMar DeRozan:
    - derozan
    - demar
    - debo
    - compton's finest

  Luka Doncic:
    - luka
    - doncic
    - the don
    - wonderboy
    # Negative
    - fat luka
    - chubby luka
    - whiny luka

  Kevin Durant:
    - kd
    - durant
    - durantula
    - slim reaper
    - easy money sniper
    # Negative
    - cupcake
    - snake
    - bus rider

  Anthony Edwards:
    - ant
    - edwards
    - antman
    - a1 from day 1

  Joel Embiid:
    - embiid
    - the process
    - jojo
    - do a 180
    - troel
    # Negative
    - jobiid
    - emflop
    - the processor

  De'Aaron Fox:
    - de'aaron
    - fox
    - swipa

  Evan Fournier:
    - fournier
    - dont google

  Darius Garland:
    - garland
    - dg

  Paul George:
    - pg
    - paul george
    - george
    - pg13
    # Negative
    - playoff p
    - pandemic p
    - wayoff p
    - pushoff p

  Shai Gilgeous-Alexander:
    - sga
    - shai
    - gilgeous-alexander

  Rudy Gobert:
    - gobert
    - rudy
    - stifle tower
    - gobzilla
    # Negative
    - rudymentary
    - covid rudy
    - microphone rudy

  Aaron Gordon:
    - aaron gordon
    - gordon

  Draymond Green:
    - draymond
    - green
    - dray
    - bdd
    - day day
    # Negative
    - donkey
    - nut puncher
    - triple single

  Tyrese Haliburton:
    - haliburton
    - hali
    - haliban
    - halipotter

  James Harden:
    - harden
    - the beard
    # Negative
    - james floppen
    - james soften
    - literally hitler

  Josh Hart:
    - hart

  Scoot Henderson:
    - scoot henderson
    - scoot

  Tyler Herro:
    - herro
    - boy wonder

  Chet Holmgren:
    - chet
    - holmgren
    - unicorn

  Jrue Holiday:
    - jrue
    - holiday

  Dwight Howard:
    - dwight
    - howard
    - superman
    - d12

  Brandon Ingram:
    - ingram
    - bi
    - slim reefer
    - sleepy b

  Kyrie Irving:
    - kyrie
    - irving
    - kai
    - uncle drew
    - world b flat
    # Negative
    - flat earther
    - mr sage
    - third eye
    - antisemite
    - antivaxxer
    - anti vax

  LeBron James:
    - lebron
    - bron
    - lbj
    - james
    - the king
    - chosen one
    # Negative (le- prefix variants don't contain "lebron")
    - lemickey
    - lebrick
    - lechoke
    - leflop
    - lefraud
    - lequit
    - lestatpad
    - lecoast
    - legm
    - lediva
    - letravel
    - leturnover
    - legoat
    - washed king
    - china bron

  Nikola Jokic:
    - jokic
    - joker
    - chokic
    - big honey
    - sombor shuffle

  Tre Jones:
    - tre jones

  Caris LeVert:
    - levert
    - caris

  Kawhi Leonard:
    - kawhi
    - leonard
    - the klaw
    - board man
    - fun guy
    # Negative
    - load management
    - robot kawhi

  Damian Lillard:
    - lillard
    - dame
    - dame time
    - dame dolla
    - logo lillard

  Zach LaVine:
    - lavine
    - zach

  Kevon Looney:
    - looney
    - loon

  Brook Lopez:
    - brook lopez
    - lopez
    - splash mountain

  Tyrese Maxey:
    - maxey

  De'Anthony Melton:
    - melton

  Khris Middleton:
    - middleton
    - khris
    - khash money

  Donovan Mitchell:
    - donovan mitchell
    - mitchell
    - spida

  Ja Morant:
    - morant
    - ja
    - temetrius
    # Negative
    - glock morant
    - ja moron
    - moron-t

  Dejounte Murray:
    - dejounte
    - murray

  Jamal Murray:
    - jamal murray
    - jamal
    - blue arrow

  Chris Paul:
    - cp3
    - cp
    - paul
    - point god
    # Negative
    - dirty cp3
    - cone paul
    - cooked cp3

  Jordan Poole:
    - poole
    - jp
    - poole party

  Kristaps Porzingis:
    - porzingis
    - kristaps
    - kp
    - unicorn
    - tingus pingus

  Bobby Portis:
    - portis
    - crazy eyes

  Julius Randle:
    - randle
    - julius
    - beyblade

  Austin Reaves:
    - reaves
    - ar15
    - hillbilly kobe
    # Negative
    - white boy hype

  Rajon Rondo:
    - rondo
    - playoff rondo
    - connect four

  Derrick Rose:
    - drose
    - rose

  D'Angelo Russell:
    - dlo
    - russell
    - ice in my veins
    # Negative
    - snitch russell

  Domantas Sabonis:
    - sabonis
    - domas

  Alperen Sengun:
    - sengun
    - alperen
    - alp

  Pascal Siakam:
    - siakam
    - pascal
    - spicy p
    - spinakam

  Ben Simmons:
    - simmons
    - young socialite
    # Negative
    - socialite
    - pass up dunk
    - phantom injury

  Marcus Smart:
    - smart
    - marcus

  Jalen Smith:
    - jalen smith
    - stix

  Jayson Tatum:
    - tatum
    - jt
    - the problem
    # Negative
    - hero ball tatum

  Klay Thompson:
    - klay
    - thompson
    - splash brother
    - game 6 klay
    - china klay
    # Negative
    - boat klay

  Karl-Anthony Towns:
    - towns
    - kat
    # Negative
    - charmin

  Evan Turner:
    - evan turner
    - turner

  Myles Turner:
    - myles turner
    - myles

  Fred VanVleet:
    - vanvleet
    - fvv
    - steady freddy

  Franz Wagner:
    - franz wagner
    - franz

  Nikola Vucevic:
    - vucevic
    - vooch

  Kemba Walker:
    - kemba
    - cardiac kemba

  John Wall:
    - john wall
    - wall
    - j wall

  Victor Wembanyama:
    - wembanyama
    - wemby
    - alien

  Russell Westbrook:
    - westbrook
    - russ
    - brodie
    # Negative
    - westbrick
    - worstbrook
    - westbroke
    - no bbiq

  Andrew Wiggins:
    - wiggins
    - wiggs
    # Negative
    - maple jordan

  Zion Williamson:
    - zion
    - zanos
    - air gumbo
    # Negative
    - big chungas

  Trae Young:
    - trae
    - ice trae
    # Negative
    - bald spot
    - hair plugs

  Ivica Zubac:
    - zubac
    - zu
