# NBA Team Configuration for Flair Normalization
#
# Legacy codes (NJN, MKE, etc.) appear in Reddit flair prefixes like :njn-1:
# and are included as aliases for their current franchise.
#
# Excluded from mapping:
#   - Country flairs (:AUS: Australia, :CAN: Canada, etc.)
#   - Conference flairs (West, East, WC, EC)
#   - League flairs (NBA, r/NBA)
#   - Jersey numbers (23, 24, 15)
#   - Seattle SuperSonics (distinct fanbase from OKC)
#   - Disney bubble hotel flairs (GD, YC, SP8, GFL)
#   - Multi-team flairs (Mavs & Magic)

version: "2.0"
season: "2024-25"

teams:
  Atlanta Hawks:
    abbreviation: ATL
    conference: East
    aliases:
      - atl
      - hawks

  Boston Celtics:
    abbreviation: BOS
    conference: East
    aliases:
      - bos
      - celtics

  Brooklyn Nets:
    abbreviation: BKN
    conference: East
    aliases:
      - bkn
      - brk
      - njn
      - nets
      - new jersey nets

  Charlotte Hornets:
    abbreviation: CHA
    conference: East
    aliases:
      - cha
      - cho
      - hornets

  Chicago Bulls:
    abbreviation: CHI
    conference: East
    aliases:
      - chi
      - bulls

  Cleveland Cavaliers:
    abbreviation: CLE
    conference: East
    aliases:
      - cle
      - cavaliers
      - cavs

  Dallas Mavericks:
    abbreviation: DAL
    conference: West
    aliases:
      - dal
      - mavericks
      - mavs

  Denver Nuggets:
    abbreviation: DEN
    conference: West
    aliases:
      - den
      - nuggets

  Detroit Pistons:
    abbreviation: DET
    conference: East
    aliases:
      - det
      - pistons

  Golden State Warriors:
    abbreviation: GSW
    conference: West
    aliases:
      - gsw
      - warriors
      - san francisco warriors

  Houston Rockets:
    abbreviation: HOU
    conference: West
    aliases:
      - hou
      - rockets

  Indiana Pacers:
    abbreviation: IND
    conference: East
    aliases:
      - ind
      - pacers

  Los Angeles Clippers:
    abbreviation: LAC
    conference: West
    aliases:
      - lac
      - clippers
      - san diego clippers

  Los Angeles Lakers:
    abbreviation: LAL
    conference: West
    aliases:
      - lal
      - lakers

  Memphis Grizzlies:
    abbreviation: MEM
    conference: East
    aliases:
      - mem
      - grizzlies
      - vancouver grizzlies

  Miami Heat:
    abbreviation: MIA
    conference: West
    aliases:
      - mia
      - heat

  Milwaukee Bucks:
    abbreviation: MIL
    conference: East
    aliases:
      - mil
      - mke
      - bucks

  Minnesota Timberwolves:
    abbreviation: MIN
    conference: West
    aliases:
      - min
      - timberwolves
      - wolves

  New Orleans Pelicans:
    abbreviation: NOP
    conference: West
    aliases:
      - nop
      - nol
      - pelicans

  New York Knicks:
    abbreviation: NYK
    conference: East
    aliases:
      - nyk
      - knicks

  Oklahoma City Thunder:
    abbreviation: OKC
    conference: West
    aliases:
      - okc
      - thunder

  Orlando Magic:
    abbreviation: ORL
    conference: East
    aliases:
      - orl
      - magic

  Philadelphia 76ers:
    abbreviation: PHI
    conference: East
    aliases:
      - phi
      - 76ers
      - sixers

  Phoenix Suns:
    abbreviation: PHX
    conference: West
    aliases:
      - phx
      - pho
      - suns

  Portland Trail Blazers:
    abbreviation: POR
    conference: West
    aliases:
      - por
      - pdx
      - trail blazers
      - blazers

  Sacramento Kings:
    abbreviation: SAC
    conference: West
    aliases:
      - sac
      - kings

  San Antonio Spurs:
    abbreviation: SAS
    conference: West
    aliases:
      - sas
      - spurs

  Toronto Raptors:
    abbreviation: TOR
    conference: East
    aliases:
      - tor
      - tbr
      - raptors
      - tampa bay raptors

  Utah Jazz:
    abbreviation: UTA
    conference: West
    aliases:
      - uta
      - jazz

  Washington Wizards:
    abbreviation: WAS
    conference: East
    aliases:
      - was
      - wizards
      - bullets
