# NBA Team Configuration for Flair Normalization
#
# Legacy codes (NJN, MKE, etc.) appear in Reddit flair prefixes like :njn-1:
# and are included as aliases for their current franchise.
#
# Excluded from mapping:
#   - Country flairs (:AUS: Australia, :CAN: Canada, etc.)
#   - Conference flairs (West, East, WC, EC)
#   - League flairs (NBA, r/NBA)
#   - Jersey numbers (23, 24, 15)
#   - Seattle SuperSonics (distinct fanbase from OKC)
#   - Disney bubble hotel flairs (GD, YC, SP8, GFL)
#   - Multi-team flairs (Mavs & Magic)

version: "2.1"
season: "2024-25"

teams:
  Atlanta Hawks:
    abbreviation: ATL
    conference: East
    team_id: 1610612737
    logo_url: https://cdn.nba.com/logos/nba/1610612737/primary/L/logo.svg
    aliases:
      - atl
      - hawks

  Boston Celtics:
    abbreviation: BOS
    conference: East
    team_id: 1610612738
    logo_url: https://cdn.nba.com/logos/nba/1610612738/primary/L/logo.svg
    aliases:
      - bos
      - celtics

  Brooklyn Nets:
    abbreviation: BKN
    conference: East
    team_id: 1610612751
    logo_url: https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg
    aliases:
      - bkn
      - brk
      - njn
      - nets
      - new jersey nets

  Charlotte Hornets:
    abbreviation: CHA
    conference: East
    team_id: 1610612766
    logo_url: https://cdn.nba.com/logos/nba/1610612766/primary/L/logo.svg
    aliases:
      - cha
      - cho
      - hornets

  Chicago Bulls:
    abbreviation: CHI
    conference: East
    team_id: 1610612741
    logo_url: https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg
    aliases:
      - chi
      - bulls

  Cleveland Cavaliers:
    abbreviation: CLE
    conference: East
    team_id: 1610612739
    logo_url: https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg
    aliases:
      - cle
      - cavaliers
      - cavs

  Dallas Mavericks:
    abbreviation: DAL
    conference: West
    team_id: 1610612742
    logo_url: https://cdn.nba.com/logos/nba/1610612742/primary/L/logo.svg
    aliases:
      - dal
      - mavericks
      - mavs

  Denver Nuggets:
    abbreviation: DEN
    conference: West
    team_id: 1610612743
    logo_url: https://cdn.nba.com/logos/nba/1610612743/primary/L/logo.svg
    aliases:
      - den
      - nuggets

  Detroit Pistons:
    abbreviation: DET
    conference: East
    team_id: 1610612765
    logo_url: https://cdn.nba.com/logos/nba/1610612765/primary/L/logo.svg
    aliases:
      - det
      - pistons

  Golden State Warriors:
    abbreviation: GSW
    conference: West
    team_id: 1610612744
    logo_url: https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg
    aliases:
      - gsw
      - warriors
      - san francisco warriors

  Houston Rockets:
    abbreviation: HOU
    conference: West
    team_id: 1610612745
    logo_url: https://cdn.nba.com/logos/nba/1610612745/primary/L/logo.svg
    aliases:
      - hou
      - rockets

  Indiana Pacers:
    abbreviation: IND
    conference: East
    team_id: 1610612754
    logo_url: https://cdn.nba.com/logos/nba/1610612754/primary/L/logo.svg
    aliases:
      - ind
      - pacers

  Los Angeles Clippers:
    abbreviation: LAC
    conference: West
    team_id: 1610612746
    logo_url: https://cdn.nba.com/logos/nba/1610612746/primary/L/logo.svg
    aliases:
      - lac
      - clippers
      - san diego clippers

  Los Angeles Lakers:
    abbreviation: LAL
    conference: West
    team_id: 1610612747
    logo_url: https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg
    aliases:
      - lal
      - lakers

  Memphis Grizzlies:
    abbreviation: MEM
    conference: West
    team_id: 1610612763
    logo_url: https://cdn.nba.com/logos/nba/1610612763/primary/L/logo.svg
    aliases:
      - mem
      - grizzlies
      - vancouver grizzlies

  Miami Heat:
    abbreviation: MIA
    conference: East
    team_id: 1610612748
    logo_url: https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg
    aliases:
      - mia
      - heat

  Milwaukee Bucks:
    abbreviation: MIL
    conference: East
    team_id: 1610612749
    logo_url: https://cdn.nba.com/logos/nba/1610612749/primary/L/logo.svg
    aliases:
      - mil
      - mke
      - bucks

  Minnesota Timberwolves:
    abbreviation: MIN
    conference: West
    team_id: 1610612750
    logo_url: https://cdn.nba.com/logos/nba/1610612750/primary/L/logo.svg
    aliases:
      - min
      - timberwolves
      - wolves

  New Orleans Pelicans:
    abbreviation: NOP
    conference: West
    team_id: 1610612740
    logo_url: https://cdn.nba.com/logos/nba/1610612740/primary/L/logo.svg
    aliases:
      - nop
      - nol
      - pelicans

  New York Knicks:
    abbreviation: NYK
    conference: East
    team_id: 1610612752
    logo_url: https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg
    aliases:
      - nyk
      - knicks

  Oklahoma City Thunder:
    abbreviation: OKC
    conference: West
    team_id: 1610612760
    logo_url: https://cdn.nba.com/logos/nba/1610612760/primary/L/logo.svg
    aliases:
      - okc
      - thunder

  Orlando Magic:
    abbreviation: ORL
    conference: East
    team_id: 1610612753
    logo_url: https://cdn.nba.com/logos/nba/1610612753/primary/L/logo.svg
    aliases:
      - orl
      - magic

  Philadelphia 76ers:
    abbreviation: PHI
    conference: East
    team_id: 1610612755
    logo_url: https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg
    aliases:
      - phi
      - 76ers
      - sixers

  Phoenix Suns:
    abbreviation: PHX
    conference: West
    team_id: 1610612756
    logo_url: https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg
    aliases:
      - phx
      - pho
      - suns

  Portland Trail Blazers:
    abbreviation: POR
    conference: West
    team_id: 1610612757
    logo_url: https://cdn.nba.com/logos/nba/1610612757/primary/L/logo.svg
    aliases:
      - por
      - pdx
      - trail blazers
      - blazers

  Sacramento Kings:
    abbreviation: SAC
    conference: West
    team_id: 1610612758
    logo_url: https://cdn.nba.com/logos/nba/1610612758/primary/L/logo.svg
    aliases:
      - sac
      - kings

  San Antonio Spurs:
    abbreviation: SAS
    conference: West
    team_id: 1610612759
    logo_url: https://cdn.nba.com/logos/nba/1610612759/primary/L/logo.svg
    aliases:
      - sas
      - spurs

  Toronto Raptors:
    abbreviation: TOR
    conference: East
    team_id: 1610612761
    logo_url: https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg
    aliases:
      - tor
      - tbr
      - raptors
      - tampa bay raptors

  Utah Jazz:
    abbreviation: UTA
    conference: West
    team_id: 1610612762
    logo_url: https://cdn.nba.com/logos/nba/1610612762/primary/L/logo.svg
    aliases:
      - uta
      - jazz

  Washington Wizards:
    abbreviation: WAS
    conference: East
    team_id: 1610612764
    logo_url: https://cdn.nba.com/logos/nba/1610612764/primary/L/logo.svg
    aliases:
      - was
      - wizards
      - bullets
